@echo off
cd C:\Users\danie\Documents\New-ROI-Calculators
echo Testing DeepSeek API connection...
echo This may take a few seconds...
echo.
node test-deepseek-api.mjs
echo.
echo Press any key to close this window...
pause > nul
